#!/bin/bash
#SBATCH -N 2
#SBATCH -C cpu
#SBATCH -q debug
#SBATCH -J mpitest
#SBATCH --ntasks-per-node=20
#SBATCH -t 0:30:00


#run the application:

srun -N 2 --ntasks-per-node=20 ./mpi -n 1000 -s 1 -o mpi_2_20.out

num="1000 10000 100000 1000000 6000000"

for i in $num 
    do
        srun -N 2 --ntasks-per-node=20 ./mpi -n $i >> mpi_2_20_results.out
    done
